--ARQUIVO
INSERT INTO BANK_DATA(AGENCY,ACCOUNT_NUMBER,BALANCE,CREATED_AT, UPDATED_AT) values('123','456',20.00,SYSDATE,SYSDATE );
INSERT INTO COSTUMERS(NAME,CPF,CREATED_AT, UPDATED_AT) values('DIEGO','12312312387',SYSDATE,SYSDATE );
INSERT INTO USERS(BANK_DATA_ID,COSTUMER_ID,PASSWORD,CREATED_AT, UPDATED_AT) values(1,1,'$2a$10$sFKmbxbG4ryhwPNx/l3pgOJSt.fW1z6YcUnuE2X8APA/Z3NI/oSpq',SYSDATE,SYSDATE );

